version: "3.9"

services:
  etherfi-syncing-client:
    build: .
    volumes:
      - ./storage:/_storage_
    environment:
      ETHERFI_SC_IPFS_GATEWAY: "https://ether-fi-goerli.infura-ipfs.io/ipfs"
      ETHERFI_SC_GRAPH_URL: "https://api.studio.thegraph.com/query/41778/goerli-32eth/v0.0.1"
      ETHERFI_SC_OUTPUT_LOCATION: "/_storage_/output"
      ETHERFI_SC_BIDDER: "0xF88866238ecE28A41e050b04360423a5d1181d49"
      ETHERFI_SC_PRIVATE_KEYS_FILE_LOCATION: "/_storage_/input/privateEtherfiKeystore-1681911458600.json"
      ETHERFI_SC_PASSWORD: "Password123!"
    restart: on-failure